spring:
  datasource:
    url: jdbc:mysql://identity-db.cbnyz7f21ihs.us-east-1.rds.amazonaws.com:3306/identity-db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: qkGQmELceTj0vciBzPJf
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect:
          org.hibernate.dialect: MySQL5Dialect
server:
  port: 8081

jwt:
  secret: 482B4D6251655468576D5A7134743777217A25432A46294A404E635266556A58
  expiration-time: 1800000
