spring:
  application:
    name: saving-goals-service
  profiles:
    active: default
  cloud:
    config:
      name: saving-goals-service
  config:
    import: optional:configserver:http://3.85.123.230:8888