server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
       git:
         uri: https://github.com/larissalana/save-for-you-tcc-puc
         searchPaths: backend/configs-repo*
         clone-on-start: true
         default-label: main